name: Publish to GitHub Container Registry
on: [push, workflow_dispatch]

jobs:
  push_to_ghcr:
    name: Push Docker image to ghcr
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=category::publish
            echo ::set-output name=kind::release
            echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
          elif [[ $GITHUB_REF == refs/heads/master ]]; then
            echo ::set-output name=category::ignore
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo ::set-output name=category::ignore
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            echo ::set-output name=category::publish
            echo ::set-output name=kind::branch-build
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            VERSION_SAFE_BRANCH_NAME=${BRANCH_NAME/\//-}
            echo ::set-output name=version::${VERSION_SAFE_BRANCH_NAME}-${GITHUB_RUN_NUMBER}
          else
            echo ::set-output name=category::ignore
          fi
          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=docker_image::ghcr.io/mikemoraned/rust_multi_arch
      
      - name: Information
        run: |
          echo git_ref=$GITHUB_REF
          echo git_sha=$GITHUB_SHA
          echo category=${{ steps.prepare.outputs.category }}
          echo version=${{ steps.prepare.outputs.version }}
          echo kind=${{ steps.prepare.outputs.kind }}
          echo date=${{ steps.prepare.outputs.build_date }}
          echo docker_image=${{ steps.prepare.outputs.docker_image }}

      - name: Login to ghcr
        if: steps.prepare.outputs.category == 'publish'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up QEMU
        if: steps.prepare.outputs.category == 'publish'
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        if: steps.prepare.outputs.category == 'publish'
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        if: steps.prepare.outputs.category == 'publish'
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build and Push
        if: steps.prepare.outputs.category == 'publish'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          tags: "${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}"
          labels: "KIND=${{ steps.prepare.outputs.kind }},BUILD_DATE=${{ steps.prepare.outputs.build_date }},VCS_REF=${GITHUB_SHA}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      
